import assert from 'node:assert/strict';
import {createDrone,commandDrone,updateDrone,scanEntities} from './dist/drone-system.js';
import {formationSlot} from './dist/squadron.js';
const home=[0,2,0],operator=[90,2,-30],d=createDrone();let battery=100;
commandDrone(d,'FOLLOW',home,battery);
for(let i=0;i<1000;i++)battery=updateDrone(d,.02,{home,followHome:operator,battery,formationOffset:[0,8,0],idleMotion:false}).battery;
assert(Math.hypot(d.pos[0]-90,d.pos[2]+30)<1,'FOLLOW uses operator anchor');
commandDrone(d,'ORBIT',home,battery);
for(let i=0;i<1600;i++)battery=updateDrone(d,.02,{home,followHome:operator,battery,formationOffset:formationSlot('ORBIT','scout',0,i*.02),idleMotion:false}).battery;
assert(Math.hypot(d.pos[0]-90,d.pos[2]+30)<18,'ORBIT uses operator anchor');
commandDrone(d,'HOLD',home,battery);const hold=[...d.pos];
for(let i=0;i<200;i++)battery=updateDrone(d,.02,{home,followHome:[200,2,100],battery}).battery;
assert(Math.hypot(...d.pos.map((v,i)=>v-hold[i]))<1,'HOLD does not follow moving operator');
commandDrone(d,'RETURN HOME',home,battery);
for(let i=0;i<2400&&d.mode!=='DOCK';i++)battery=updateDrone(d,.02,{home,followHome:operator,battery}).battery;
assert.equal(d.mode,'DOCK');assert.deepEqual(d.pos,home);
const readings=scanEntities({...createDrone(),pos:[0,2,0]},[{id:'warm',kind:'HOSTILE',x:0,y:2,z:-10}],{type:'personal',sensor:'thermal'});
assert.equal(readings[0]?.sensor,'thermal','wearable scanner measures heat without Utility airframe');
console.log('PASS: separate escort/dock anchors, physical orbit and return, HOLD authority, wearable thermal readings.');
